### ISSUE TITLE
View count not working 

### ISSUE THREAD

**Issue by rashed1995** [aazztech/directorist#2092]
### Directorist version

v8

### Description

View count not working 

### Steps to reproduce

https://www.youtube.com/watch?v=iBSoJ_6FrNY

### Isolating the problem

- [X] I have reproduced this bug in localhost.
- [X] This bug happens with a default WordPress theme active (eg. 2021, 2022 etc).

**Comment by rashed1995** [comment]
Username: directorist
Password: directorist.3540.1!
Login at https://cbo-bizhub.com/wp-admin/

Issue can be found in this site.

**Comment by HeyMehedi** [comment]
Issues related to themes, and fixes will be available in the next release. 

Commit: https://github.com/sovware/drealestate/commit/605cdb05befe3b1765b0350f32c726935df280ea
