### ISSUE TITLE
Google Maps zoom in/out buttons.

### ISSUE THREAD

**Issue by talhaarefin** [aazztech/directorist#2123]
### Directorist version

V8

### Description

The zoom in/out buttons on Google Maps views within the platform are not displayed, making it challenging to navigate the map.

### Steps to reproduce

https://prnt.sc/rvr5fIzzMVkt

### Isolating the problem

- [X] I have reproduced this bug in localhost.
- [ ] This bug happens with a default WordPress theme active (eg. 2021, 2022 etc).

**Comment by RabbiIslamRony** [comment]
@talhaarefin resolved
