### ISSUE TITLE
Google Map- Zoom in Zoom out 

### ISSUE THREAD

**Issue by rashed1995** [aazztech/directorist#2144]
### Directorist version

8.0.7

### Description

The zoom-in and zoon-out buttons are missing from Google Map. 
 

### Steps to reproduce

All listing page
Single listing page

### Isolating the problem

- [X] I have reproduced this bug in localhost.
- [X] This bug happens with a default WordPress theme active (eg. 2021, 2022 etc).

**Comment by RabbiIslamRony** [comment]
@Armanul46

**Comment by RabbiIslamRony** [comment]
Resolved
