### ISSUE TITLE
Overflow-y missing at custom single listing page selector

### ISSUE THREAD

**Issue by rashed1995** [aazztech/directorist#2147]
### Directorist version

8.0.7

### Description

Demonstration, https://www.loom.com/share/cc2d03c26ea142c4a449647c5c97baa9

### Steps to reproduce

Demonstration, https://www.loom.com/share/cc2d03c26ea142c4a449647c5c97baa9

### Isolating the problem

- [X] I have reproduced this bug in localhost.
- [X] This bug happens with a default WordPress theme active (eg. 2021, 2022 etc).

**Comment by RabbiIslamRony** [comment]
@iamibrahimriaz
