### ISSUE TITLE
Tags not being used in search when typed into text field.

### ISSUE THREAD

**Issue by bendruitt** [aazztech/directorist#55]
Not sure if this is default behaviour but when I search for a listing by typing a tag into the "What are you looking for?" text field no results are returned. Using version 6.2.2.

**Comment by aazztech** [comment]
Hi,
This is a default behaviour. Directorist has a different field to search listing by tag.

**Comment by bendruitt** [comment]
Not sure that it's a great default behaviour. Thinking about meta-tags in web pages is a good example of how tags can improve search results without needing to specify a 'tag search' specifically. Perhaps you could have an option to search tags also when using the text field, would, I believe, be more in line with user expectations (although I've been wrong before!)?
